Cybersecurity Trainee |Penetration Testing | Always learning and building üöÄ

# Hi, I'm Omar Mazen üëã
üéì Computer Engineer | red team Trainee  
üîç Interested in Penetration Testing, and Network Offensive
üìö Security+ |  | Google Cybersecurity Certificate  
üõ†Ô∏è Learning everyday, building practical skills in Offensive Security
<!--
## üíª Projects:
- Security+ Notes
- Pentesting Labs -->

## üöÄ Edu:
- CompTIA A+
- CompTIA linux+
- CompTIA Network+
- CompTIA Security+
- Cisco Certified Network Associate
- Certified Ethical Hacker 
- Google Cybersecurity Certificate  
- TryHackMe & Hack The Box Labs

## üì´ Contact me:
- Email: omar.mazen.work@gmail.com
- LinkedIn: OmarMazen

<!---
lomarsalahl/lomarsalahl is a ‚ú® special ‚ú® repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->

"event": "Configuration file loaded: /home/adminuser/venv/lib/python3.11/site-packages/readmeai/config/settings/ignore_list.toml",
"level": "info",
"logger": "readmeai.config.settings",
"timestamp": "2025-09-28T05:40:26.030861Z",
"filename": "settings.py",
"func_name": "_load_settings",
"lineno": 276
}
{
"event": "Configuration file loaded: /home/adminuser/venv/lib/python3.11/site-packages/readmeai/config/settings/languages.toml",
"level": "info",
"logger": "readmeai.config.settings",
"timestamp": "2025-09-28T05:40:26.031467Z",
"filename": "settings.py",
"func_name": "_load_settings",
"lineno": 276
}
{
"event": "Configuration file loaded: /home/adminuser/venv/lib/python3.11/site-packages/readmeai/config/settings/parsers.toml",
"level": "info",
"logger": "readmeai.config.settings",
"timestamp": "2025-09-28T05:40:26.032070Z",
"filename": "settings.py",
"func_name": "_load_settings",
"lineno": 276
}
{
"event": "Configuration file loaded: /home/adminuser/venv/lib/python3.11/site-packages/readmeai/config/settings/prompts.toml",
"level": "info",
"logger": "readmeai.config.settings",
"timestamp": "2025-09-28T05:40:26.032879Z",
"filename": "settings.py",
"func_name": "_load_settings",
"lineno": 276
}
{
"event": "Configuration file loaded: /home/adminuser/venv/lib/python3.11/site-packages/readmeai/config/settings/tool_config.toml",
"level": "info",
"logger": "readmeai.config.settings",
"timestamp": "2025-09-28T05:40:26.036980Z",
"filename": "settings.py",
"func_name": "_load_settings",
"lineno": 276
}
{
"event": "Configuration file loaded: /home/adminuser/venv/lib/python3.11/site-packages/readmeai/config/settings/tooling.toml",
"level": "info",
"logger": "readmeai.config.settings",
"timestamp": "2025-09-28T05:40:26.038161Z",
"filename": "settings.py",
"func_name": "_load_settings",
"lineno": 276
}
{
"event": "Pydantic settings: dict_keys(['config', 'ignore_list', 'languages', 'parsers', 'prompts', 'tool_config', 'tooling'])",
"level": "info",
"logger": "readmeai.cli.main",
"timestamp": "2025-09-28T05:40:26.039549Z",
"filename": "main.py",
"func_name": "main",
"lineno": 86
}
{
"event": "Repository settings: repository='https://github.com/eli64s/readme-ai' full_name='eli64s/readme-ai' host_domain='github.com' host='github' name='readme-ai'",
"level": "info",
"logger": "readmeai.cli.main",
"timestamp": "2025-09-28T05:40:26.039724Z",
"filename": "main.py",
"func_name": "main",
"lineno": 87
}
{
"event": "LLM API settings: api='OPENAI' base_url='https://api.openai.com/v1/chat/completions' context_window=3900 encoder='cl100k_base' host_name=Url('https://api.openai.com/') localhost=Url('http://localhost:11434/') model='gpt-3.5-turbo' path='v1/chat/completions' temperature=0.1 tokens=699 top_p=0.9",
"level": "info",
"logger": "readmeai.cli.main",
"timestamp": "2025-09-28T05:40:26.039881Z",
"filename": "main.py",
"func_name": "main",
"lineno": 88
}
{
"event": "Total files analyzed: 90",
"level": "info",
"logger": "readmeai.__main__",
"timestamp": "2025-09-28T05:40:27.768458Z",
"filename": "__main__.py",
"func_name": "log_repository_context",
"lineno": 102
}
{
"event": "Metadata extracted: {'cicd': {'github_actions': '.github/workflows/release-pipeline.yml, .github/workflows/mkdocs.yml, .github/workflows/release-drafter.yml, .github/workflows/coverage.yml'}, 'containers': {'docker': 'Dockerfile'}, 'documentation': {'mkdocs': '.github/workflows/mkdocs.yml'}, 'package_managers': {'poetry': 'poetry.lock', 'pip': 'setup/requirements.txt', 'conda': 'setup/environment.yaml'}}",
"level": "info",
"logger": "readmeai.__main__",
"timestamp": "2025-09-28T05:40:27.768609Z",
"filename": "__main__.py",
"func_name": "log_repository_context",
"lineno": 103
}
{
"event": "Dependencies: ['github_actions', 'docker', 'mkdocs', 'poetry', 'pip', 'conda', 'quickstart.toml', 'requirements.txt', 'mkdocs.yml', 'pyproject.toml', 'emojis.yaml', 'language-map.toml', 'project-manifest.toml', 'environment.yaml', 'dockerfile', 'shell', 'prompts.toml', 'templates.toml', 'coverage.yml', 'python', 'release-drafter.yml', 'commands.toml', 'config.toml', 'dev-tools.toml', 'headers.toml', 'ignore-list.toml', 'poetry.lock', 'makefile', 'release-pipeline.yml', 'banners.toml', 'badge-list.toml', 'dev-setup.toml', 'aiohttp', 'coverage', 'openai', 'typing-extensions', 'pytest-cov', 'pytest-randomly', 'mkdocs-material', 'pytest', 'anthropic', 'pytest-memray', 'mkdocs-redirects', 'pytest-asyncio', 'click', 'tomli', 'pre-commit', 'mypy', 'tenacity', 'pytest-mock', 'pytest-sugar', 'pymdown-extensions', 'mkdocs-git-revision-date-localized-plugin', 'tiktoken', 'pytest-xdist', 'gitpython', 'pydantic-settings', 'mkdocstrings-python', 'pytest-fastest', 'pydantic', 'structlog', 'python', 'types-pyyaml', 'mkdocs-minify-plugin', 'ruff', 'types-toml', 'pyyaml', 'google-generativeai', 'nox', 'pydantic-extra-types', 'mkdocs', 'pytest-pretty', 'python: 3.11-slim-buster']",
"level": "info",
"logger": "readmeai.__main__",
"timestamp": "2025-09-28T05:40:27.768839Z",
"filename": "__main__.py",
"func_name": "log_repository_context",
"lineno": 104
}
{
"event": "Languages: {'lock': 1, 'toml': 14, 'py': 60, 'yml': 5, 'yaml': 2, 'sh': 5, 'txt': 1}",
"level": "info",
"logger": "readmeai.__main__",
"timestamp": "2025-09-28T05:40:27.769032Z",
"filename": "__main__.py",
"func_name": "log_repository_context",
"lineno": 105
}
Traceback (most recent call last):
File "/home/adminuser/venv/lib/python3.11/site-packages/readmeai/__main__.py", line 32, in error_handler
yield
File "/home/adminuser/venv/lib/python3.11/site-packages/readmeai/__main__.py", line 40, in readme_agent
asyncio.run(readme_generator(config, output_file))
File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
return runner.run(main)
^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
return self._loop.run_until_complete(task)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
return future.result()
^^^^^^^^^^^^^^^
File "/home/adminuser/venv/lib/python3.11/site-packages/readmeai/__main__.py", line 55, in readme_generator
async with ModelFactory.get_backend(config, context).use_api() as llm:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/adminuser/venv/lib/python3.11/site-packages/readmeai/models/factory.py", line 41, in get_backend
return llm_service(config, context)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/adminuser/venv/lib/python3.11/site-packages/readmeai/models/openai.py", line 31, in __init__
self._model_settings()
File "/home/adminuser/venv/lib/python3.11/site-packages/readmeai/models/openai.py", line 43, in _model_settings
self.client = openai.OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/adminuser/venv/lib/python3.11/site-packages/openai/_client.py", line 105, in __init__
raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/home/adminuser/venv/bin/readmeai", line 8, in <module>
sys.exit(main())
^^^^^^
File "/home/adminuser/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/adminuser/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/home/adminuser/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/adminuser/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
return __callback(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/adminuser/venv/lib/python3.11/site-packages/readmeai/cli/main.py", line 90, in main
readme_agent(config=config, output_file=output)
File "/home/adminuser/venv/lib/python3.11/site-packages/readmeai/__main__.py", line 39, in readme_agent
with error_handler():
File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
self.gen.throw(typ, value, traceback)
File "/home/adminuser/venv/lib/python3.11/site-packages/readmeai/__main__.py", line 34, in error_handler
raise ReadmeGeneratorError(e) from e
readmeai.errors.ReadmeGeneratorError: Error generating README: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
